//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorLibreria
{
    using System;
    
    public enum Estados : int
    {
        Entregado = 0,
        Devuelto = 1,
        Dañado = 2
    }
}
