//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialPrestamo
    {
        public int Id { get; set; }
        public string LibroEjemplarCodigo { get; set; }
        public string ClientesIdentificacion { get; set; }
        public System.DateTime Fecha_Ini { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public Estados Estado { get; set; }
    
        public virtual LibroEjemplar LibroEjemplar { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
