//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libros()
        {
            this.LibroAutor = new HashSet<LibroAutor>();
            this.LibroEjemplar = new HashSet<LibroEjemplar>();
        }
    
        public string ISBN { get; set; }
        public string Titulo { get; set; }
        public string Pais { get; set; }
        public string Stock { get; set; }
        public string Editorial { get; set; }
        public int CategoriaId { get; set; }
    
        public virtual Categorias Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroAutor> LibroAutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LibroEjemplar> LibroEjemplar { get; set; }
    }
}
