//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorLibreria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibreriaModelContainer : DbContext
    {
        public LibreriaModelContainer()
            : base("name=LibreriaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Libros> LibrosSet { get; set; }
        public virtual DbSet<Categorias> CategoriasSet { get; set; }
        public virtual DbSet<Autores> AutoresSet { get; set; }
        public virtual DbSet<LibroAutor> LibroAutorSet { get; set; }
        public virtual DbSet<LibroEjemplar> LibroEjemplarSet { get; set; }
        public virtual DbSet<Clientes> ClientesSet { get; set; }
        public virtual DbSet<Direccion> DireccionSet { get; set; }
        public virtual DbSet<HistorialPrestamo> HistorialPrestamoSet { get; set; }
        public virtual DbSet<Variables> VariablesSet { get; set; }
        public virtual DbSet<Credenciales> CredencialesSet { get; set; }
    }
}
