//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorLibreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroAutor
    {
        public int Id { get; set; }
        public string LibroISBN { get; set; }
        public int AutorId { get; set; }
    
        public virtual Libros Libros { get; set; }
        public virtual Autores Autores { get; set; }
    }
}
